services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    container_name: pinecone_standalone
    environment:
      - PORT=5080
      - INDEX_TYPE=serverless
      - DIMENSION=384
      - METRIC=cosine
    ports:
      - "5080:5080"
    platform: linux/amd64